#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

git clone https://github.com/NSLS-II/edrixs.git
cp -r edrixs/examples .
cp examples/sphinx/example_*.py .
sphx_glr_python_to_jupyter.py example_*.py
rm -r edrixs
