#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager@^2.0.0 --no-build
jupyter labextension install @bokeh/jupyter_bokeh@^2.0.0 --no-build
jupyter labextension install jupyter-matplotlib@^0.7.2 --no-build
jupyter lab build -y
jupyter lab clean -y
npm cache clean --force

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

mkdir source_code
mv * source_code/.
cp source_code/examples .

wget https://nsls-ii.github.io/edrixs/_downloads/7fdbd8c6d7eb529642f9d6214b5c2159/auto_examples_jupyter.zip
unzip *.zip
grep -RiIl 'matplotlib inline' | xargs sed -i 's/matplotlib inline/matplotlib widget/g'

